---
circuit_images:
    - type: "CSA"
      image_type: "svg"
      image: "CSA.svg"
      width: 80
      height: 128
    - type: "nand2"
      image_type: "png"
      image: "nand2.png"
      width: 80
      height: 24
    - type: "nand3"
      image_type: "png"
      image: "nand2.png"
      width: 80
      height: 32
    - type: "nor2"
      width: 80
      height: 24
    - type: "nor3"
      width: 80
      height: 32
    - type: "and2"
      image_type: "svg"
      image: "and.svg"
      width: 80
      height: 40
    - type: "and3"
      image_type: "svg"
      image: "and.svg"
      width: 80
      height: 48
    - type: "or2"
      width: 80
      height: 40
    - type: "buffer"
      image_type: "svg"
      image: "buffer.svg"
      width: 80
      height: 32
    - type: "inverter"
      image_type: "svg"
      image: "buffer.svg"
      width: 80
      height: 16
    - type: "halfAdd"
      image_type: "svg"
      image: "adder.svg"
      width: 80
      height: 80
    - type: "fullAdd"
      image_type: "svg"
      image: "adder.svg"
      width: 80
      height: 128
    - type: "fullAdd_x"
      image_type: "svg"
      image: "adder.svg"
      width: 80
      height: 216
    - type: "fullAdd_i"
      image_type: "svg"
      image: "adder.svg"
      width: 80
      height: 96
    - type: "maj"
      width: 80
      hieght: 104
    - type: "min"
      width: 80
      height: 48
    - type: "r4be"
      image_type: "svg"
      image: "mux.svg"
      width: 80
      height: 168
    - type: "r4bs"
      image_type: "svg"
      image: "mux.svg"
      width: 80
      height: 128
    - type: "sumxor"
      image_type: "svg"
      image: "xor.svg"
      width: 80
      height: 24
    - type: "sum_b"
      width: 80
      height: 48
    - type: "xor2"
      image_type: "svg"
      image: "xor.svg"
      width: 80
      height: 56
    - type: "xor3"
      image_type: "svg"
      image: "xor.svg"
      width: 80
      height: 112
    - type: "xnor2"
      image_type: "svg"
      image: "xor.svg"
      width: 80
      height: 56
    - type: "grayCell"
      height: 48
      fill: "gray"
    - type: "blackCell"
      height: 88
      fill: "#232323"

defaults:
    image_type: "TextRect"
    label: name
    width: 80
    fill: "#cccccc"
    scale_mode: none
...
