---
circuit_images:
    - type: "CSA"
      image_type: "svg"
      image: "CSA.svg"
      width: 80
      height: 128
    - type: "nand2"
      image_type: "png"
      image: "nand2.png"
      width: 80
      height: 24
...
