---
circuit_images:
    - type: "CSA"
      width: 80
      height: 128
    - type: "nand2"
      width: 80
      height: 24
    - type: "nand3"
      width: 80
      height: 32
    - type: "nor2"
      image_type: "TextRect"
      width: 80
      height: 24
    - type: "nor3"
      image_type: "TextRect"
      width: 80
      height: 32
    - type: "and2"
      image_type: "TextRect"
      width: 80
      height: 40
    - type: "and3"
      image_type: "TextRect"
      width: 80
      height: 48
    - type: "or2"
      image_type: "TextRect"
      width: 80
      height: 40
    - type: "buffer"
      image_type: "TextRect"
      width: 80
      height: 32
      fill: "#8eb77a"
    - type: "inverter"
      image_type: "TextRect"
      width: 80
      height: 16
      fill: "#94d4dd"
    - type: "halfAdd"
      image_type: "TextRect"
      width: 80
      height: 80
      fill: "#c1a8dd"
    - type: "fullAdd"
      image_type: "TextRect"
      width: 80
      height: 128
      fill: "#dda8cc"
    - type: "fullAdd_x"
      image_type: "TextRect"
      width: 80
      height: 216
      fill: "#dda8b9"
    - type: "fullAdd_i"
      image_type: "TextRect"
      width: 80
      height: 96
      fill: "#dda8c5"
    - type: "maj"
      image_type: "TextRect"
      width: 80
      hieght: 104
    - type: "min"
      image_type: "TextRect"
      width: 80
      height: 48
    - type: "r4be"
      image_type: "TextRect"
      width: 80
      height: 168
    - type: "r4bs"
      image_type: "TextRect"
      width: 80
      height: 128
      fill: "#a8a8dd"
    - type: "sumxor"
      image_type: "TextRect"
      width: 80
      height: 24
    - type: "sum_b"
      image_type: "TextRect"
      width: 80
      height: 48
    - type: "xor2"
      image_type: "TextRect"
      width: 80
      height: 56
      fill: "#ddaca8"
    - type: "xor3"
      image_type: "TextRect"
      width: 80
      height: 112
      fill: "#ddaca8"
    - type: "xnor2"
      image_type: "TextRect"
      width: 80
      fill: "#ddaca8"
      height: 56

defaults:
    image_type: "TextRect"
    label: name
    fill: "green"
    scale_mode: none
...
